apps/pokeApp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

app_name = 'poke'
urlpatterns = [
    url(r'^$', views.index, name="home"),
    url(r'^register/$', views.register, name="register"),
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^pokes/$', views.pokes, name="pokes"),
    url(r'^pokes/(?P<userId>[0-9]+)/$', views.pokeUser, name="pokeUser")   
]

poke/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^',include('apps.pokeApp.urls')),
    url(r'^admin/', admin.site.urls),
]

apps/pokeApp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import bcrypt
import re

# Create your models here.
class UserManager(models.Manager) :
   

    def register(self,post):
        errorMsgs = []
        user = {}
        returnVal = {}
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]')

        if post['name'] == "" :
            errorMsgs.append({'message': 'Name is required', 'extra_tags':"register"})
        elif len(post['name']) < 3 :
            errorMsgs.append({'message':'Name has to be minimum 3 characters long', 'extra_tags':"register"})

        if post['alias'] == "" :
            errorMsgs.append({'message':'alias is required', 'extra_tags':"register"})
        elif len(post['alias']) < 3 :
            errorMsgs.append({'message':'alias has to be minimum 3 characters long', 'extra_tags':"register"})

        if not post['alias']:
		    error = {'message': 'Email is required', 'extra_tags': 'register'}
		    errorMsgs.append(error)
        elif not EMAIL_REGEX.match(post['email']):
			error = {'message': 'Invalid email address', 'extra_tags': 'register'}
			errorMsgs.append(error)
		
        if post['password'] == "" :
            errorMsgs.append({'message':'password is required', 'extra_tags':"register"})
        elif len(post['password']) < 8:
            errorMsgs.append({'message':'Password has to be mininum 8 characters long', 'extra_tags':"register"})
            print "password less than 8"      
        elif post['password'] != post['confirm_password'] :
            errorMsgs.append({'message':'Passwords do not match.', 'extra_tags':"register"})
            print "password mismatch"

        if 'birth_date' not in post or post['birth_date'] == "":
		    error = {'message': 'Please select birth date', 'extra_tags': 'register'}
		    errorMsgs.append(error)
        # elif post['birth_date'] == "":
		# 	error = {'message': 'Invalid birth date', 'extra_tags': 'register'}
		# 	errorMsgs.append(error)

        try: 
            user = Users.objects.get(email = post['email'])
            print "user: ", user
            errorMsgs.append({'message':'User with {} email already exists.'.format(post['email']), 'extra_tags':"register"})
            print "user exists"
            error = True
        except Users.DoesNotExist:
            if (len(errorMsgs) == 0):
                hash1 = bcrypt.hashpw(post['password'].encode(), bcrypt.gensalt())
                user = Users.objects.create(name=post['name'], alias=post['alias'], email=post['email'], password = hash1, birth_date=post['birth_date'], receivedPokes=0)
                print "added user"
                print "User does not exist"
                
        returnVal = {'user':user,'errors':errorMsgs}
        return returnVal

    def login (self, post) :
        errorMsgs = []
        user = {}
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]')

        if post['login_email'] == "" :
            errorMsgs.append({'message':'username is required', 'extra_tags':"login"})
        if post['login_password'] == "" :
            errorMsgs.append({'message':'password is required', 'extra_tags':"login"})
        if not EMAIL_REGEX.match(post['login_email']) :
            errorMsgs.append({'message':'Invalid email', 'extra_tags':"login"})

        if (len(errorMsgs) == 0):
            try :
                user = Users.objects.get(email = post['login_email'])
                print user
                print user.password
                if bcrypt.checkpw(post['login_password'].encode(), user.password.encode()):
                    print "login successful"
                else: 
                    print "password mismatch"
                    errorMsgs.append({'message':'Incorrect User Id or Password. Please try again', 'extra_tags':'login'})
                    user = {}
            except Users.DoesNotExist:
                print "user not found"
                errorMsgs.append({'message':'Incorrect User Id or Password. Please try again', 'extra_tags':'login'})

        return {'user': user, 'errors': errorMsgs}

class PokeManager(models.Manager) :
    def pokeUser(self, receiverId, pokerId):
        # Get the receiver of the poke
        receiver = Users.objects.get(pk=receiverId)
        print "reciever: ", receiver
        # Get the poker
        poker =  Users.objects.get(pk=pokerId)

        # If this is receiver's first poke then create an entry in the Pokes table,
        # else update the poke count
        pokeEntry = Pokes.objects.filter(receiver=receiver, poker=poker)
        print "pokeEntry ", pokeEntry
        if (len(pokeEntry)==0) :
            newPoke = Pokes.objects.create(receiver=receiver, poker=poker, numPokesByPoker=1)
            print "Created new poke: ", newPoke
        else :
            pokeEntry[0].numPokesByPoker += 1
            pokeEntry[0].save()
            print "Updated poke: ", pokeEntry
        
        # Update receiver's receivedPokes
        receiver.receivedPokes += 1
        receiver.save() 

class Users(models.Model):
    name = models.CharField(max_length=255)
    alias = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=8)
    birth_date = models.DateTimeField('date hired')
    receivedPokes = models.IntegerField()
    objects = UserManager()
    def __str__(self):
        return "{} {} {} {}".format(self.name, self.alias, self.email, self.password) 

class Pokes(models.Model):
    name = models.CharField(max_length=255)
    receiver = models.ForeignKey('Users', related_name = "pokes")
    poker = models.ForeignKey('Users', related_name = "poked_by")
    numPokesByPoker = models.IntegerField()
    objects = PokeManager()
    def __str__(self):
        return "{} {} {}".format(self.receiver.name, self.poker.name, self.numPokesByPoker) 

apps/pokeApp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from .models import *
import re
import bcrypt
from django.utils import timezone
from django.contrib import messages
from django.db.models import Q

# Create your views here.
def index (request) :  
    return render(request, 'pokeApp/index.html')

def register(request) :
    error = False
    context = {}
    print "in register"

    if request.method == "POST":
        print request.POST

        returnVal = Users.objects.register(request.POST)
        if returnVal['user'] :
            request.session['logged_in_user'] = returnVal['user'].id
            print "logged in user: ",request.session['logged_in_user']
            return redirect(reverse('poke:pokes'))
        else :
            for error in returnVal['errors'] :
                print error
                messages.error(request,error['message'],extra_tags=error['extra_tags'])
            return redirect(reverse("poke:home"))

def login (request):
    if request.method == "POST":
        returnVal = Users.objects.login(request.POST)
        if returnVal['user']:
            request.session['logged_in_user'] = returnVal['user'].id
            print "logged in user: ",request.session['logged_in_user']
            return redirect(reverse('poke:pokes'))
        else:
            for error in returnVal['errors'] :
                print error
                messages.error(request,error['message'],extra_tags=error['extra_tags'])
            return redirect(reverse('poke:home'))

def logout (request) :
    request.session.flush()
    return redirect(reverse('poke:home'))

def pokes(request):

    numPeople = 0
    user = __getLoggedUser(request)
    user_name = user.name
    print "user name: ", user_name

    # Get my pokers
    myPokerHistory = Pokes.objects.filter(receiver = user).order_by('-numPokesByPoker')
    numPeople = len(myPokerHistory)
    print myPokerHistory

    # Get other users that I can poke
    users = Users.objects.filter(~Q(id = user.id))
    print users
    context = {
        'numPeople' : numPeople,
        'user_name': user_name,
        'users' : users,
        'history' : myPokerHistory
    } 
    return render(request, 'pokeApp/pokes.html', context)

def pokeUser(request, userId) :

    if request.method == "POST":
        Pokes.objects.pokeUser(userId, request.session['logged_in_user'])

    return redirect(reverse('poke:pokes'))

# Private functions

def __getLoggedUser(request): 
    user = None
    id = request.session['logged_in_user']
    try:
        user = Users.objects.get(pk=id)
        return user
    except Users.DoesNotExist:
        messages.add_message(request, messages.ERROR, 'You are not logged in. Please log in to continue')
        print "Not logged in"
        return redirect(reverse('wishList:home'))
    return user

apps/pokeApp/templates/pokeApp/index.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'pokeApp/css/style.css' %}">
    <title>User Dashboard</title>
</head>
<body>
    <div id="container">
        <h2>Welcome!</h2>
        <div class="row">
            <div class="col-md-6 indexLegend">
               
                <form action="{% url 'poke:register' %}" method="post" class="form-horizontal">
                    {% csrf_token %}
                    <fieldset class="scheduler-border">
                        <legend class="scheduler-border">Register</legend>
                        <div>
                            <label for="name">Name:</label>
                            <input type="text" name="name" maxlength="255">
                        </div>
                        <div>
                            <label for="alias">Alias:</label>
                            <input type="text" name="alias" maxlength="255">
                        </div>
                        <div>
                            <label for="email">Email Address:</label>
                            <input type="text" name="email" maxlength="255">
                        </div>
                        <div>
                            <label for="password">Password:</label>
                            <input type="text" name="password">
                            <p>The password should be at least 8 characters long</p>
                        </div>
                        <div>
                            <label for="confirm_password">Confirm Password:</label>
                            <input type="text" name="confirm_password">
                        </div>
                        <div>
                            <label for="birth_date">Hire Date:</label>
                            <input type="Date" name="birth_date">
                        </div>
                        {% if messages %}
                        <ul>
                            {% for message in messages %}
                                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR and 'register' in message.tags %}
                                    <li{% if message.tags %} class="{{ message.tags}} messages alert alert-danger" {% endif %}>{{ message }}</li>
                                {% elif 'register_successful' in message.tags %}
                                    <li class="alert alert-success">{{message}}</li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                        {% endif %}
                        
                        <input type="submit" name="register" value="Register" class="btn btn-primary indexButton">
                    </fieldset>
                </form>
            </div>
            <div class="col-md-6">
                <form action="{% url 'poke:login' %}" method="POST" class="form-horizontal">
                    {% csrf_token %}
                    <fieldset class="scheduler-border">
                        <legend class="scheduler-border">Login</legend>
                        <div>
                            <label for="user_email">Email Address:</label>
                            <input type="text" name="login_email">
                        </div>
                        <div>
                            <label for="login_password">Password:</label>
                            <input type="text" name="login_password">
                        </div>
                        {% if messages %}
                        <ul>
                            {% for message in messages %}
                                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR and 'login' in message.tags %}
                                    <li{% if message.tags %} class="{{ message.tags}} messages alert alert-danger" {% endif %}>{{ message }}</li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <input type="submit" name="login" value="Log In" class="btn btn-primary indexButton">
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

apps/pokeApp/templates/pokeApp/pokes.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'pokeApp/css/style.css' %}">
    <title>User Dashboard</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-right">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'poke:logout' %}">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
    <div id="container">
        <h2>Welcome, <span class="colorRed">{{user_name}}</span>!</h2>
        <p>{{numPeople}} people poked you!</p>
        <div class="row">
            <div class="col-md-6 history">
                {% for entry in history %}
                    <p>{{entry.poker.name}} poked you {{entry.numPokesByPoker}} times</p>
                {% endfor %}
            </div>
        </div>    
        <div class="row">
            <div class="col-md-12">
                <h4>People you may want to poke</h4>
                <table class="table-bordered">
                    <tr>
                        <th>Name</th>
                        <th>Alias</th>
                        <th>Email Address</th>
                        <th>Poke History</th>
                        <th>Action</th>
                    </tr>
                    {% for user in users %}                    
                        <tr>
                            <td>{{user.name}}</a></td>
                            <td>{{user.alias}}</td>
                            <td>{{user.email}}</td>
                            <td>{{user.receivedPokes}}</td>
                            <td>
                                <form action="{% url 'poke:pokeUser' user.id %}" method="POST" class="form-horizontal">
                                    {% csrf_token %}
                                    <input type="submit" name="poke" value="Poke" class="btn btn-primary">
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>  
    </div>
</body>
</html>